version: "3.7"

services:
  postgres:
    image: postgres:11
    env_file: .env.development
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "54432:5432"

  django:
    build:
      context: .
      dockerfile: Dockerfile.django
    env_file: .env.development
    volumes:
      - ./src:/app
    ports:
      - "8080:8080"

volumes:
  pgdata:
